/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'desserts' : IDL.Null,
  'other' : IDL.Null,
  'food' : IDL.Null,
  'snacks' : IDL.Null,
  'beverages' : IDL.Null,
});
export const MenuItemInput = IDL.Record({
  'name' : IDL.Text,
  'category' : Category,
  'imageId' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
});
export const Unit = IDL.Variant({
  'kg' : IDL.Null,
  'ml' : IDL.Null,
  'gram' : IDL.Null,
  'liter' : IDL.Null,
  'piece' : IDL.Null,
});
export const RawMaterialInput = IDL.Record({
  'lowStockThreshold' : IDL.Float64,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'unit' : Unit,
  'quantity' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const RawMaterial = IDL.Record({
  'id' : IDL.Text,
  'lowStockThreshold' : IDL.Float64,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : Unit,
  'quantity' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isAvailable' : IDL.Bool,
  'category' : Category,
  'imageId' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Int,
  'totalSales' : IDL.Float64,
  'lowStockMaterials' : IDL.Vec(RawMaterial),
  'outOfStockItems' : IDL.Vec(MenuItem),
  'totalInventoryItems' : IDL.Int,
});
export const OrderStatus = IDL.Variant({ 'completed' : IDL.Null });
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'menuItemName' : IDL.Text,
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
  'menuItemId' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Text,
});
export const RecipeIngredient = IDL.Record({
  'materialId' : IDL.Text,
  'quantityNeeded' : IDL.Float64,
});
export const OrderItemInput = IDL.Record({
  'quantity' : IDL.Float64,
  'menuItemId' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'createdBy' : IDL.Text,
  'items' : IDL.Vec(OrderItemInput),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustRawMaterialQuantity' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuItem' : IDL.Func([MenuItemInput], [IDL.Text], []),
  'createRawMaterial' : IDL.Func([RawMaterialInput], [IDL.Text], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'deleteRawMaterial' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([IDL.Int, IDL.Int], [IDL.Vec(Order)], ['query']),
  'getRawMaterial' : IDL.Func([IDL.Text], [IDL.Opt(RawMaterial)], ['query']),
  'getRecipe' : IDL.Func([IDL.Text], [IDL.Vec(RecipeIngredient)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRecipes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RecipeIngredient)))],
      ['query'],
    ),
  'listLowStockMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
  'listMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'listRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
  'placeOrder' : IDL.Func([OrderInput], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRecipe' : IDL.Func([IDL.Text, IDL.Vec(RecipeIngredient)], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItemInput], [], []),
  'updateRawMaterial' : IDL.Func([IDL.Text, RawMaterialInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'desserts' : IDL.Null,
    'other' : IDL.Null,
    'food' : IDL.Null,
    'snacks' : IDL.Null,
    'beverages' : IDL.Null,
  });
  const MenuItemInput = IDL.Record({
    'name' : IDL.Text,
    'category' : Category,
    'imageId' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
  });
  const Unit = IDL.Variant({
    'kg' : IDL.Null,
    'ml' : IDL.Null,
    'gram' : IDL.Null,
    'liter' : IDL.Null,
    'piece' : IDL.Null,
  });
  const RawMaterialInput = IDL.Record({
    'lowStockThreshold' : IDL.Float64,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'unit' : Unit,
    'quantity' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const RawMaterial = IDL.Record({
    'id' : IDL.Text,
    'lowStockThreshold' : IDL.Float64,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : Unit,
    'quantity' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isAvailable' : IDL.Bool,
    'category' : Category,
    'imageId' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Int,
    'totalSales' : IDL.Float64,
    'lowStockMaterials' : IDL.Vec(RawMaterial),
    'outOfStockItems' : IDL.Vec(MenuItem),
    'totalInventoryItems' : IDL.Int,
  });
  const OrderStatus = IDL.Variant({ 'completed' : IDL.Null });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
  const OrderItem = IDL.Record({
    'menuItemName' : IDL.Text,
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
    'menuItemId' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Text,
  });
  const RecipeIngredient = IDL.Record({
    'materialId' : IDL.Text,
    'quantityNeeded' : IDL.Float64,
  });
  const OrderItemInput = IDL.Record({
    'quantity' : IDL.Float64,
    'menuItemId' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'createdBy' : IDL.Text,
    'items' : IDL.Vec(OrderItemInput),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustRawMaterialQuantity' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuItem' : IDL.Func([MenuItemInput], [IDL.Text], []),
    'createRawMaterial' : IDL.Func([RawMaterialInput], [IDL.Text], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'deleteRawMaterial' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([IDL.Int, IDL.Int], [IDL.Vec(Order)], ['query']),
    'getRawMaterial' : IDL.Func([IDL.Text], [IDL.Opt(RawMaterial)], ['query']),
    'getRecipe' : IDL.Func([IDL.Text], [IDL.Vec(RecipeIngredient)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRecipes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RecipeIngredient)))],
        ['query'],
      ),
    'listLowStockMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
    'listMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'listRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
    'placeOrder' : IDL.Func([OrderInput], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRecipe' : IDL.Func([IDL.Text, IDL.Vec(RecipeIngredient)], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItemInput], [], []),
    'updateRawMaterial' : IDL.Func([IDL.Text, RawMaterialInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };