/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'desserts' : null } |
  { 'other' : null } |
  { 'food' : null } |
  { 'snacks' : null } |
  { 'beverages' : null };
export interface DashboardStats {
  'totalOrders' : bigint,
  'todaySales' : number,
  'totalSales' : number,
  'pendingOrdersCount' : bigint,
  'lowStockMaterials' : Array<RawMaterial>,
  'outOfStockItems' : Array<MenuItemFull>,
  'totalInventoryItems' : bigint,
  'todayOrders' : bigint,
}
export interface MenuItemFull {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'quantity' : number,
  'category' : Category,
  'imageId' : [] | [string],
  'price' : number,
}
export interface MenuItemInput {
  'name' : string,
  'description' : string,
  'quantity' : number,
  'category' : Category,
  'imageId' : [] | [string],
  'price' : number,
}
export interface OrderFull {
  'id' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : bigint,
  'createdBy' : string,
  'totalAmount' : number,
  'items' : Array<OrderItem>,
  'orderNumber' : string,
  'customerName' : [] | [string],
  'customerPhone' : [] | [string],
  'isTransferred' : boolean,
  'transferredTo' : [] | [string],
}
export interface OrderInput {
  'paymentMethod' : PaymentMethod,
  'createdBy' : string,
  'items' : Array<OrderItemInput>,
}
export interface OrderItem {
  'menuItemName' : string,
  'quantity' : number,
  'unitPrice' : number,
  'menuItemId' : string,
}
export interface OrderItemInput { 'quantity' : number, 'menuItemId' : string }
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null };
export interface RawMaterial {
  'id' : string,
  'lowStockThreshold' : number,
  'supplierName' : string,
  'name' : string,
  'createdAt' : bigint,
  'unit' : Unit,
  'quantity' : number,
  'costPrice' : number,
}
export interface RawMaterialInput {
  'lowStockThreshold' : number,
  'supplierName' : string,
  'name' : string,
  'unit' : Unit,
  'quantity' : number,
  'costPrice' : number,
}
export interface RecipeIngredient {
  'materialId' : string,
  'quantityNeeded' : number,
}
export interface SalesReport {
  'startTime' : bigint,
  'itemBreakdown' : Array<SalesReportItem>,
  'totalOrders' : bigint,
  'endTime' : bigint,
  'totalRevenue' : number,
}
export interface SalesReportItem {
  'menuItemName' : string,
  'quantitySold' : number,
  'totalRevenue' : number,
  'menuItemId' : string,
}
export type Unit = { 'kg' : null } |
  { 'ml' : null } |
  { 'gram' : null } |
  { 'liter' : null } |
  { 'piece' : null };
export interface UserProfile {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[string], undefined>,
  'adjustRawMaterialQuantity' : ActorMethod<[string, number], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOrder' : ActorMethod<[string], undefined>,
  'transferOrder' : ActorMethod<[string, string], boolean>,
  'createMenuItem' : ActorMethod<[MenuItemInput], string>,
  'createRawMaterial' : ActorMethod<[RawMaterialInput], string>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'deleteRawMaterial' : ActorMethod<[string], undefined>,
  'editOrderItems' : ActorMethod<[string, Array<OrderItemInput>], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMenuItem' : ActorMethod<[string], [] | [MenuItemFull]>,
  'getOrder' : ActorMethod<[string], [] | [OrderFull]>,
  'getOrders' : ActorMethod<[bigint, bigint], Array<OrderFull>>,
  'getRawMaterial' : ActorMethod<[string], [] | [RawMaterial]>,
  'getRecipe' : ActorMethod<[string], Array<RecipeIngredient>>,
  'getSalesReport' : ActorMethod<[bigint, bigint], SalesReport>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveOrders' : ActorMethod<[], Array<OrderFull>>,
  'listAllRecipes' : ActorMethod<[], Array<[string, Array<RecipeIngredient>]>>,
  'listLowStockMaterials' : ActorMethod<[], Array<RawMaterial>>,
  'listMenuItems' : ActorMethod<[], Array<MenuItemFull>>,
  'listPendingOrders' : ActorMethod<[], Array<OrderFull>>,
  'listRawMaterials' : ActorMethod<[], Array<RawMaterial>>,
  'placeOrder' : ActorMethod<[OrderInput], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRecipe' : ActorMethod<[string, Array<RecipeIngredient>], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[string], boolean>,
  'updateMenuItem' : ActorMethod<[string, MenuItemInput], undefined>,
  'updateRawMaterial' : ActorMethod<[string, RawMaterialInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];