/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RawMaterial {
    id: string;
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    createdAt: bigint;
    unit: Unit;
    quantity: number;
    costPrice: number;
}
export interface SalesReportItem {
    menuItemName: string;
    quantitySold: number;
    totalRevenue: number;
    menuItemId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    menuItemName: string;
    quantity: number;
    unitPrice: number;
    menuItemId: string;
}
export interface OrderItemInput {
    quantity: number;
    menuItemId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OrderInput {
    paymentMethod: PaymentMethod;
    createdBy: string;
    items: Array<OrderItemInput>;
}
export interface DashboardStats {
    totalOrders: bigint;
    todaySales: number;
    totalSales: number;
    pendingOrdersCount: bigint;
    lowStockMaterials: Array<RawMaterial>;
    outOfStockItems: Array<MenuItemFull>;
    totalInventoryItems: bigint;
    todayOrders: bigint;
}
export interface MenuItemInput {
    name: string;
    description: string;
    quantity: number;
    category: Category;
    imageId?: string;
    price: number;
}
export interface RecipeIngredient {
    materialId: string;
    quantityNeeded: number;
}
export interface RawMaterialInput {
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    unit: Unit;
    quantity: number;
    costPrice: number;
}
export interface OrderFull {
    id: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: bigint;
    createdBy: string;
    totalAmount: number;
    items: Array<OrderItem>;
    orderNumber: string;
    customerName: string | null;
    customerPhone: string | null;
    isTransferred: boolean;
    transferredTo: string | null;
}
export interface SalesReport {
    startTime: bigint;
    itemBreakdown: Array<SalesReportItem>;
    totalOrders: bigint;
    endTime: bigint;
    totalRevenue: number;
}
export interface MenuItemFull {
    id: string;
    name: string;
    createdAt: bigint;
    isAvailable: boolean;
    description: string;
    quantity: number;
    category: Category;
    imageId?: string;
    price: number;
}
export interface UserProfile {
    id: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    desserts = "desserts",
    other = "other",
    food = "food",
    snacks = "snacks",
    beverages = "beverages"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    accepted = "accepted"
}
export enum PaymentMethod {
    upi = "upi",
    cash = "cash"
}
export enum Unit {
    kg = "kg",
    ml = "ml",
    gram = "gram",
    liter = "liter",
    piece = "piece"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptOrder(id: string): Promise<void>;
    adjustRawMaterialQuantity(id: string, adjustment: number): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeOrder(id: string): Promise<void>;
    transferOrder(id: string, targetPos: string): Promise<boolean>;
    createMenuItem(input: MenuItemInput): Promise<string>;
    createRawMaterial(input: RawMaterialInput): Promise<string>;
    deleteMenuItem(id: string): Promise<void>;
    deleteRawMaterial(id: string): Promise<void>;
    editOrderItems(id: string, newItems: Array<OrderItemInput>): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMenuItem(id: string): Promise<MenuItemFull | null>;
    getOrder(id: string): Promise<OrderFull | null>;
    getOrders(startIndex: bigint, pageSize: bigint): Promise<Array<OrderFull>>;
    getRawMaterial(id: string): Promise<RawMaterial | null>;
    getRecipe(menuItemId: string): Promise<Array<RecipeIngredient>>;
    getSalesReport(startTime: bigint, endTime: bigint): Promise<SalesReport>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveOrders(): Promise<Array<OrderFull>>;
    listAllRecipes(): Promise<Array<[string, Array<RecipeIngredient>]>>;
    listLowStockMaterials(): Promise<Array<RawMaterial>>;
    listMenuItems(): Promise<Array<MenuItemFull>>;
    listPendingOrders(): Promise<Array<OrderFull>>;
    listRawMaterials(): Promise<Array<RawMaterial>>;
    placeOrder(input: OrderInput): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRecipe(menuItemId: string, ingredients: Array<RecipeIngredient>): Promise<void>;
    toggleMenuItemAvailability(id: string): Promise<boolean>;
    updateMenuItem(id: string, input: MenuItemInput): Promise<void>;
    updateRawMaterial(id: string, input: RawMaterialInput): Promise<void>;
}
import type { Category as _Category, DashboardStats as _DashboardStats, MenuItemFull as _MenuItemFull, MenuItemInput as _MenuItemInput, OrderFull as _OrderFull, OrderInput as _OrderInput, OrderItem as _OrderItem, OrderItemInput as _OrderItemInput, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, RawMaterial as _RawMaterial, RawMaterialInput as _RawMaterialInput, Unit as _Unit, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrder(arg0);
            return result;
        }
    }
    async adjustRawMaterialQuantity(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustRawMaterialQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustRawMaterialQuantity(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOrder(arg0);
            return result;
        }
    }
    async transferOrder(arg0: string, arg1: string): Promise<boolean> {
        if (this.actor !== null) {
            try {
                const result = await this.actor.transferOrder(arg0, arg1);
                return result;
            } catch(e) {
                console.error('transferOrder error:', e);
                throw e;
            }
        }
        const result = await this.actor!.transferOrder(arg0, arg1);
        return result;
    }
    async createMenuItem(arg0: MenuItemInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuItem(to_candid_MenuItemInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuItem(to_candid_MenuItemInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRawMaterial(arg0: RawMaterialInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRawMaterial(to_candid_RawMaterialInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRawMaterial(to_candid_RawMaterialInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMenuItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteRawMaterial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterial(arg0);
            return result;
        }
    }
    async editOrderItems(arg0: string, arg1: Array<OrderItemInput>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.editOrderItems(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editOrderItems(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItem(arg0: string): Promise<MenuItemFull | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<OrderFull | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(arg0: bigint, arg1: bigint): Promise<Array<OrderFull>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders(arg0, arg1);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders(arg0, arg1);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRawMaterial(arg0: string): Promise<RawMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterial(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterial(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: string): Promise<Array<RecipeIngredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return result;
        }
    }
    async getSalesReport(arg0: bigint, arg1: bigint): Promise<SalesReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesReport(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveOrders(): Promise<Array<OrderFull>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveOrders();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveOrders();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllRecipes(): Promise<Array<[string, Array<RecipeIngredient>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllRecipes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllRecipes();
            return result;
        }
    }
    async listLowStockMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLowStockMaterials();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLowStockMaterials();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMenuItems(): Promise<Array<MenuItemFull>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMenuItems();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMenuItems();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingOrders(): Promise<Array<OrderFull>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingOrders();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingOrders();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRawMaterials();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRawMaterials();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: OrderInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderInput_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderInput_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setRecipe(arg0: string, arg1: Array<RecipeIngredient>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRecipe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRecipe(arg0, arg1);
            return result;
        }
    }
    async toggleMenuItemAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMenuItemAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMenuItemAvailability(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: string, arg1: MenuItemInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItemInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItemInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRawMaterial(arg0: string, arg1: RawMaterialInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRawMaterial(arg0, to_candid_RawMaterialInput_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRawMaterial(arg0, to_candid_RawMaterialInput_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItemFull_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItemFull): MenuItemFull {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OrderFull_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderFull): OrderFull {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_RawMaterial_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RawMaterial): RawMaterial {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Unit_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Unit): Unit {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItemFull]): MenuItemFull | null {
    return value.length === 0 ? null : from_candid_MenuItemFull_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderFull]): OrderFull | null {
    return value.length === 0 ? null : from_candid_OrderFull_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RawMaterial]): RawMaterial | null {
    return value.length === 0 ? null : from_candid_RawMaterial_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalOrders: bigint;
    todaySales: number;
    totalSales: number;
    pendingOrdersCount: bigint;
    lowStockMaterials: Array<_RawMaterial>;
    outOfStockItems: Array<_MenuItemFull>;
    totalInventoryItems: bigint;
    todayOrders: bigint;
}): {
    totalOrders: bigint;
    todaySales: number;
    totalSales: number;
    pendingOrdersCount: bigint;
    lowStockMaterials: Array<RawMaterial>;
    outOfStockItems: Array<MenuItemFull>;
    totalInventoryItems: bigint;
    todayOrders: bigint;
} {
    return {
        totalOrders: value.totalOrders,
        todaySales: value.todaySales,
        totalSales: value.totalSales,
        pendingOrdersCount: value.pendingOrdersCount,
        lowStockMaterials: from_candid_vec_n23(_uploadFile, _downloadFile, value.lowStockMaterials),
        outOfStockItems: from_candid_vec_n28(_uploadFile, _downloadFile, value.outOfStockItems),
        totalInventoryItems: value.totalInventoryItems,
        todayOrders: value.todayOrders
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    createdAt: bigint;
    unit: _Unit;
    quantity: number;
    costPrice: number;
}): {
    id: string;
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    createdAt: bigint;
    unit: Unit;
    quantity: number;
    costPrice: number;
} {
    return {
        id: value.id,
        lowStockThreshold: value.lowStockThreshold,
        supplierName: value.supplierName,
        name: value.name,
        createdAt: value.createdAt,
        unit: from_candid_Unit_n26(_uploadFile, _downloadFile, value.unit),
        quantity: value.quantity,
        costPrice: value.costPrice
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    isAvailable: boolean;
    description: string;
    quantity: number;
    category: _Category;
    imageId: [] | [string];
    price: number;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    isAvailable: boolean;
    description: string;
    quantity: number;
    category: Category;
    imageId?: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        isAvailable: value.isAvailable,
        description: value.description,
        quantity: value.quantity,
        category: from_candid_Category_n31(_uploadFile, _downloadFile, value.category),
        imageId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.imageId)),
        price: value.price
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    createdAt: bigint;
    createdBy: string;
    totalAmount: number;
    items: Array<_OrderItem>;
    orderNumber: string;
    customerName?: [] | [string];
    customerPhone?: [] | [string];
    isTransferred?: boolean;
    transferredTo?: [] | [string];
}): {
    id: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: bigint;
    createdBy: string;
    totalAmount: number;
    items: Array<OrderItem>;
    orderNumber: string;
    customerName: string | null;
    customerPhone: string | null;
    isTransferred: boolean;
    transferredTo: string | null;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n38(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n40(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        totalAmount: value.totalAmount,
        items: value.items,
        orderNumber: value.orderNumber,
        customerName: (value.customerName && value.customerName.length > 0) ? value.customerName[0] : null,
        customerPhone: (value.customerPhone && value.customerPhone.length > 0) ? value.customerPhone[0] : null,
        isTransferred: value.isTransferred ?? false,
        transferredTo: (value.transferredTo && value.transferredTo.length > 0) ? value.transferredTo[0] : null,
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    ml: null;
} | {
    gram: null;
} | {
    liter: null;
} | {
    piece: null;
}): Unit {
    return "kg" in value ? Unit.kg : "ml" in value ? Unit.ml : "gram" in value ? Unit.gram : "liter" in value ? Unit.liter : "piece" in value ? Unit.piece : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desserts: null;
} | {
    other: null;
} | {
    food: null;
} | {
    snacks: null;
} | {
    beverages: null;
}): Category {
    return "desserts" in value ? Category.desserts : "other" in value ? Category.other : "food" in value ? Category.food : "snacks" in value ? Category.snacks : "beverages" in value ? Category.beverages : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RawMaterial>): Array<RawMaterial> {
    return value.map((x)=>from_candid_RawMaterial_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItemFull>): Array<MenuItemFull> {
    return value.map((x)=>from_candid_MenuItemFull_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderFull>): Array<OrderFull> {
    return value.map((x)=>from_candid_OrderFull_n36(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItemInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItemInput): _MenuItemInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_RawMaterialInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RawMaterialInput): _RawMaterialInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Unit_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): _Unit {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    quantity: number;
    category: Category;
    imageId?: string;
    price: number;
}): {
    name: string;
    description: string;
    quantity: number;
    category: _Category;
    imageId: [] | [string];
    price: number;
} {
    return {
        name: value.name,
        description: value.description,
        quantity: value.quantity,
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        imageId: value.imageId ? candid_some(value.imageId) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    unit: Unit;
    quantity: number;
    costPrice: number;
}): {
    lowStockThreshold: number;
    supplierName: string;
    name: string;
    unit: _Unit;
    quantity: number;
    costPrice: number;
} {
    return {
        lowStockThreshold: value.lowStockThreshold,
        supplierName: value.supplierName,
        name: value.name,
        unit: to_candid_Unit_n16(_uploadFile, _downloadFile, value.unit),
        quantity: value.quantity,
        costPrice: value.costPrice
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    createdBy: string;
    items: Array<OrderItemInput>;
}): {
    paymentMethod: _PaymentMethod;
    createdBy: string;
    items: Array<_OrderItemInput>;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n46(_uploadFile, _downloadFile, value.paymentMethod),
        createdBy: value.createdBy,
        items: value.items
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    desserts: null;
} | {
    other: null;
} | {
    food: null;
} | {
    snacks: null;
} | {
    beverages: null;
} {
    return value == Category.desserts ? {
        desserts: null
    } : value == Category.other ? {
        other: null
    } : value == Category.food ? {
        food: null
    } : value == Category.snacks ? {
        snacks: null
    } : value == Category.beverages ? {
        beverages: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): {
    kg: null;
} | {
    ml: null;
} | {
    gram: null;
} | {
    liter: null;
} | {
    piece: null;
} {
    return value == Unit.kg ? {
        kg: null
    } : value == Unit.ml ? {
        ml: null
    } : value == Unit.gram ? {
        gram: null
    } : value == Unit.liter ? {
        liter: null
    } : value == Unit.piece ? {
        piece: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
